config/routes.rb
Gridfs::Application.routes.draw do
  resources :blogors

  resources :blogs
  if Rails.env.development?
    match "/upload/grid/uploads/*path" => "gridfs#serve"
  end

end

app/models/blog.rb
require 'carrierwave/mongoid'
class Blog
  include Mongoid::Document
  field :name
  field :content
  field :file
  mount_uploader :file, FileUploader
end

app/models/blogor.rb
class Blogor
  include Mongoid::Document
  field :name, type: String
  field :content, type: String
  field :file
  mount_uploader :file, FileooUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogors_controller.rb
class BlogorsController < ApplicationController
  # GET /blogors
  # GET /blogors.json
  def index
    @blogors = Blogor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogors }
    end
  end

  # GET /blogors/1
  # GET /blogors/1.json
  def show
    @blogor = Blogor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blogor }
    end
  end

  # GET /blogors/new
  # GET /blogors/new.json
  def new
    @blogor = Blogor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blogor }
    end
  end

  # GET /blogors/1/edit
  def edit
    @blogor = Blogor.find(params[:id])
  end

  # POST /blogors
  # POST /blogors.json
  def create
    @blogor = Blogor.new(params[:blogor])

    respond_to do |format|
      if @blogor.save
        format.html { redirect_to @blogor, notice: 'Blogor was successfully created.' }
        format.json { render json: @blogor, status: :created, location: @blogor }
      else
        format.html { render action: "new" }
        format.json { render json: @blogor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogors/1
  # PUT /blogors/1.json
  def update
    @blogor = Blogor.find(params[:id])

    respond_to do |format|
      if @blogor.update_attributes(params[:blogor])
        format.html { redirect_to @blogor, notice: 'Blogor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blogor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogors/1
  # DELETE /blogors/1.json
  def destroy
    @blogor = Blogor.find(params[:id])
    @blogor.destroy

    respond_to do |format|
      format.html { redirect_to blogors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])
    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.all
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/gridfs_controller.rb
class GridfsController < ApplicationController

  def serve
    gridfs_path = env["PATH_INFO"].gsub("/upload/grid/", "")
    begin
      gridfs_file = Mongoid::GridFS[gridfs_path]
      self.response_body = gridfs_file.data
      self.content_type = gridfs_file.content_type
    rescue
      self.status = :file_not_found
      self.content_type = 'text/plain'
      self.response_body = ''
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogors_helper.rb
module BlogorsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/gridfs_helper.rb
module GridfsHelper
end

app/views/blogors/_form.html.erb
<%= form_for(@blogor) do |f| %>
  <% if @blogor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogor.errors.count, "error") %> prohibited this blogor from being saved:</h2>

      <ul>
      <% @blogor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
    <div class="field">
      <%= f.label :file %><br />
      <%= f.file_field :file %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogors/edit.html.erb
<h1>Editing blogor</h1>

<%= render 'form' %>

<%= link_to 'Show', @blogor %> |
<%= link_to 'Back', blogors_path %>

app/views/blogors/index.html.erb
<h1>Listing blogors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogors.each do |blogor| %>
  <tr>
    <td><%= blogor.name %></td>
    <td><%= blogor.content %></td>
    <td><%= link_to 'Show', blogor %></td>
    <td><%= link_to 'Edit', edit_blogor_path(blogor) %></td>
    <td><%= link_to 'Destroy', blogor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blogor', new_blogor_path %>

app/views/blogors/new.html.erb
<h1>New blogor</h1>

<%= render 'form' %>

<%= link_to 'Back', blogors_path %>

app/views/blogors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @blogor.name %>
</p>

<p>
  <b>Content:</b>
  <%= @blogor.content %>
</p>

<p>
  <b>Content:</b>
  <%= @blogor.file %>
</p>



<%= link_to 'Edit', edit_blogor_path(@blogor) %> |
<%= link_to 'Back', blogors_path %>
# mongodb.conf

# Where to store the data.

# Note: if you run mongodb as a non-root user (recommended) you may
# need to create and set permissions for this directory manually,
# e.g., if the parent directory isn't mutable by the mongodb user.
dbpath=/var/lib/mongodb

#where to log
logpath=/var/log/mongodb/mongodb.log

logappend=true

#port = 27017

# Disables write-ahead journaling
# nojournal = true

# Enables periodic logging of CPU utilization and I/O wait
#cpu = true

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
    <div class="field">
      <%= f.label :file %><br />
      <%= f.file_field :file %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.name %></td>
    <td><%= blog.content %></td>
    <td><%= link_to 'Show', blog %></td>
    <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
    <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to "Download", blog.file_url %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @blog.name %>
</p>

<p>
  <b>Content:</b>
  <%= @blog.content %>
</p>

<p>
  <b>Content:</b>
  <%= link_to "Download", @blog.file_url %>
</p>
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gridfs</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>